db.apps.insert({ name: "Flarum", repo: "" });
db.apps.insert({ name: "Mumble", repo: "" });
db.apps.insert({ name: "ReactionCommerce", repo: "reactioncommerce/reaction" });
db.apps.insert({ name: "Gogs", repo: "gogits/gogs" });
db.apps.insert({ name: "Journey", repo: "kabukky/journey" });
db.apps.insert({ disabled: true, name: "Sandstorm.io" });
db.apps.insert({ disabled: true, name: "Ghost" });
db.apps.insert({ disabled: true, name: "ethersheet" });
db.apps.insert({ disabled: true, name: "rizzoma" });
db.apps.insert({ disabled: true, name: "junta" });
db.apps.insert({ disabled: true, name: "metamaps" });
db.apps.insert({ disabled: true, name: "apache wave" });
db.apps.insert({ disabled: true, name: "gitorius" });
db.apps.insert({ disabled: true, name: "etherpad" });
db.apps.insert({ disabled: true, name: "taiga.io" });
db.apps.insert({ disabled: true, name: "ownCloud" });
db.apps.insert({ disabled: true, name: "loomio" });
db.apps.insert({ disabled: true, name: "Kaiwa" });
db.apps.insert({ disabled: true, name: "Apache OFBiz" });
db.apps.insert({ disabled: true, name: "Apache Roller" });
db.apps.insert({ disabled: true, name: "Jclouds" });
db.apps.insert({ disabled: true, name: "Codiad" });
db.apps.insert({ disabled: true, name: "Apache Tomcat" });
db.apps.insert({ disabled: true, name: "Streisand" });
db.apps.insert({ disabled: true, name: "Diaspora" });
db.apps.insert({ disabled: true, name: "Discourse" });
db.apps.insert({ disabled: true, name: "Brooklyn" });
db.apps.insert({ disabled: true, name: "Vault" });
db.apps.insert({ disabled: true, name: "HabitRPG" });
db.apps.insert({ disabled: true, name: "Preconfigured, Prethemed Jekyll 100% free for Github pages" });
db.apps.insert({ disabled: true, name: "Syncthing" });
db.apps.insert({ disabled: true, name: "piwik" });
db.apps.insert({ disabled: true, name: "invoice-ninja" });
db.apps.insert({ disabled: true, name: "Hugo preconfigured & prethemed like Jekyll & optimized for GH pages" });
db.apps.insert({ disabled: true, name: "gocd" });
db.apps.insert({ disabled: true, name: "Sylius" });
db.apps.insert({ disabled: true, name: "gitlab-ci" });
db.apps.insert({ disabled: true, name: "Apache Spark" });
db.apps.insert({ disabled: true, name: "Graylog" });
db.apps.insert({ disabled: true, name: "OctoberCMS" });
db.apps.insert({ disabled: true, name: "Mermaid" });
db.apps.insert({ disabled: true, name: "Joomla" });
db.apps.insert({ disabled: true, name: "Medium-editor" });
db.apps.insert({ disabled: true, name: "Seafile" });
db.apps.insert({ disabled: true, name: "PrestaShop" });
db.apps.insert({ disabled: true, name: "Mapnik" });
db.apps.insert({ disabled: true, name: "hexo" });
db.apps.insert({ disabled: true, name: "druid-io/druid" });
db.apps.insert({ disabled: true, name: "sirius" });
db.apps.insert({ disabled: true, name: "OpenRefine" });
db.apps.insert({ disabled: true, name: "Phaser" });
db.apps.insert({ disabled: true, name: "vanilla" });
db.apps.insert({ disabled: true, name: "sandstorm.io" });
db.apps.insert({ disabled: true, name: "onionshare" });
db.apps.insert({ disabled: true, name: "exercism.io" });
db.apps.insert({ disabled: true, name: "tiddlywiki5" });
db.apps.insert({ disabled: true, name: "bitcore" });
db.apps.insert({ disabled: true, name: "Mail In A Box" });
db.apps.insert({ disabled: true, name: "opencart" });
db.apps.insert({ disabled: true, name: "libreboard" });
db.apps.insert({ disabled: true, name: "Taiga" });
db.apps.insert({ disabled: true, name: "OpenBazaar" });
db.apps.insert({ disabled: true, name: "codeboxide" });
db.apps.insert({ disabled: true, name: "paperwork" });
